version: 2

machine: true
jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0.12

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx100m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew check
